### ISSUE TITLE
in spi communication, why not use a static array?

### ISSUE THREAD

**Issue by xelll** [kendryte/kendryte-standalone-sdk#81]
https://github.com/kendryte/kendryte-standalone-sdk/blob/74bb90431969c55d83ce4fa2e6cd087a152b6153/lib/drivers/spi.c#L479-L480

use a static arry will reduce malloc

**Comment by zzxcanaan** [comment]
But it takes up some memory.  How do you how many memory to use?

**Comment by xelll** [comment]
> But it takes up some memory. How do you how many memory to use?

it can set as max a package use

**Comment by zzxcanaan** [comment]
However, this approach wastes memory

**Comment by xelll** [comment]
but K210 have 6MB memory

**Comment by minux** [comment]
Having a large amount of memory doesn't mean we can waste memory. (Think about program that happens to link the spi driver but otherwise doesn't use SPI.)

That being said, the API probably should be restructured so that the client passes the necessary buffer to the API. This is #49, so closing this one.
